image:
  repository: django-image
  tag: "latest"
  pullPolicy: IfNotPresent

app:
  name: django-app
  port: 8000

env:
  DJANGO_SECRET_KEY: "django-insecure-1234567890secretkey"
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"
  POSTGRES_PASSWORD: "django_password"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

ingress:
  enabled: true
  className: "nginx"
  host: "my-django.local"
  path: "/"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
