apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_SECRET_KEY: "django-insecure-1234567890secretkey"
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"

  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"
  POSTGRES_PASSWORD: "django_password"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
